In [1]:
import torch

In [2]:
dtype = torch.float32
device = torch.device('cpu')

In [3]:
# clone: 分配新内存, 生成新的张量
A = torch.arange(12, dtype=dtype, device=device).reshape((3, 4))
A

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]])

In [4]:
B = A.clone()
B

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]])

In [6]:
id(A)

5157597648

In [7]:
id(B)

5165319008

In [8]:
A * B

tensor([[  0.,   1.,   4.,   9.],
        [ 16.,  25.,  36.,  49.],
        [ 64.,  81., 100., 121.]])

In [10]:
A[0][0] = 9
A

tensor([[ 9.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]])

In [11]:
B

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]])

In [12]:
A.sum(axis=0)

tensor([21., 15., 18., 21.])

In [18]:
A.sum(axis=0, keepdims=True)  # 保留维度

tensor([[21., 15., 18., 21.]])

In [13]:
A.sum(axis=1)  # 维度变了

tensor([15., 22., 38.])

In [17]:
A.sum(axis=1, keepdims=True)  # 保留维度

tensor([[15.],
        [22.],
        [38.]])

In [15]:
A.mean(), A.sum() / A.numel()

(tensor(6.2500), tensor(6.2500))

In [19]:
A.cumsum(axis=0)  # 累加

tensor([[ 9.,  1.,  2.,  3.],
        [13.,  6.,  8., 10.],
        [21., 15., 18., 21.]])

In [22]:
# 点积: 相同位置的元素乘积之和
torch.sum(A * B)

tensor(506.)

In [36]:
# 向量积, 先按元素乘积, 对 行/列 累和
torch.mv(A, torch.ones(4))

tensor([15., 22., 38.])

In [37]:
A

tensor([[ 9.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]])

In [39]:
C = torch.arange(12, dtype=torch.float32).reshape((4, 3))
C

tensor([[ 0.,  1.,  2.],
        [ 3.,  4.,  5.],
        [ 6.,  7.,  8.],
        [ 9., 10., 11.]])

In [40]:
# 矩阵乘法
A.mm(C)

tensor([[ 42.,  57.,  72.],
        [114., 136., 158.],
        [186., 224., 262.]])

In [49]:
# L2范数(Frobenius Norm)
torch.norm(A)

tensor(24.2281)

In [50]:
A.pow(2).sum().sqrt()

tensor(24.2281)

In [54]:
# Nuclear norm: todo: what is this
torch.norm(A, p='nuc')

tensor(30.4563)